# AUTO-TAG Conda Environment Configuration
name: autotag
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - pip:
    - open-clip-torch==2.20.0
    - ultralytics==8.0.20
    - facenet-pytorch==2.5.3
    - exiftool-vendored==0.5.3
    - pyyaml>=6.0
    - tqdm>=4.65.0
    - pillow>=10.0.0
    - minio>=7.1.0
    - python-dotenv>=1.0.0  # For backward compatibility during transition
    - requests>=2.28.0